#!/usr/bin/env node
/**
 * AldraHome token pipeline (W3C DTCG + Style Dictionary)
 * ----------------------------------------------------
 * tokens/primitives.json            Tier 1  raw palette           {palette.pine.600}
 * tokens/semantic/{light,dark}.json Tier 2  shadcn/ui roles       {color.primary}, {color.muted-foreground}
 * tokens/brands/<id>/base.json      Tier 3  brand shape + type    {brand.radius.control}, {brand.font.display}
 * tokens/brands/<id>/{light,dark}   Tier 3  brand colour overrides
 *
 * Style Dictionary builds one CSS block per brand × mode:
 *
 *   [data-brand="aldra"][data-theme="dark"] { --background: ...; --primary: ...; ... }
 *
 * Outputs
 *   src/styles/tokens.css           CSS variables consumed by shadcn/ui via theme.css
 *   src/tokens/tokens.generated.ts  Typed, resolved values for Storybook docs + runtime
 *
 * Then a WCAG 2.2 contrast audit runs on every brand × mode and fails the
 * build if any foreground/background pair drops below AA.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const readJson = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));

const MODES = ['light', 'dark'];
const FLAGSHIP = 'aldra';
const brandIds = readdirSync(join(root, 'tokens/brands'), { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort((a, b) => (a === FLAGSHIP ? -1 : b === FLAGSHIP ? 1 : a.localeCompare(b)));

/* ------------------------------------------------ style dictionary setup */

// color.primary → --primary (shadcn names). brand.radius.card → --brand-radius-card.
StyleDictionary.registerTransform({
  name: 'name/aldrahome',
  type: 'name',
  transform: (token) => (token.path[0] === 'color' ? token.path.slice(1) : token.path).join('-'),
});

StyleDictionary.registerFormat({
  name: 'css/aldrahome-theme',
  format: ({ dictionary, options }) => {
    const lines = dictionary.allTokens.map((t) => `  --${t.name}: ${t.$value};`);
    return `${options.comment}\n${options.selector} {\n  color-scheme: ${options.mode};\n${lines.join('\n')}\n}\n`;
  },
});

function selectorFor(brand, mode) {
  const flagship = brand === FLAGSHIP;
  if (mode === 'light') return flagship ? `:root,\n[data-brand="${brand}"]` : `[data-brand="${brand}"]`;
  return flagship
    ? `[data-theme="dark"]:not([data-brand]),\n[data-brand="${brand}"][data-theme="dark"]`
    : `[data-brand="${brand}"][data-theme="dark"]`;
}

async function buildTheme(brand, mode, meta) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    source: [
      join(root, 'tokens/primitives.json'),
      join(root, `tokens/semantic/${mode}.json`),
      join(root, `tokens/brands/${brand}/base.json`),
      join(root, `tokens/brands/${brand}/${mode}.json`),
    ],
    platforms: {
      css: {
        transforms: ['attribute/cti', 'name/aldrahome', 'color/css', 'size/px', 'fontFamily/css', 'shadow/css/shorthand'],
        files: [
          {
            destination: 'unused.css',
            format: 'css/aldrahome-theme',
            // primitives stay internal: only semantic + brand tokens become CSS variables
            filter: (t) => t.path[0] === 'color' || t.path[0] === 'brand',
            options: { selector: selectorFor(brand, mode), mode, comment: `/* ${meta.name} · ${mode} */` },
          },
        ],
      },
    },
  });
  const [out] = await sd.formatPlatform('css');
  const { allTokens } = await sd.getPlatformTokens('css');
  const values = {};
  for (const t of allTokens.filter((t) => t.path[0] === 'color')) {
    const ref = t.original.$value;
    values[t.name] = { value: t.$value, ref: typeof ref === 'string' && ref.startsWith('{') ? ref.slice(1, -1) : null };
  }
  return { css: out.output, values };
}

const brands = [];
let css = `/* GENERATED by scripts/build-tokens.mjs from tokens/**.json (W3C DTCG). Do not edit. */\n\n`;
for (const id of brandIds) {
  const base = readJson(`tokens/brands/${id}/base.json`);
  const meta = base.$extensions['com.aldrahome.brand'];
  const modes = {};
  for (const mode of MODES) {
    const built = await buildTheme(id, mode, meta);
    css += `${built.css}\n`;
    modes[mode] = built.values;
  }
  brands.push({
    id,
    ...meta,
    font: { body: base.brand.font.body.$value.join(', '), display: base.brand.font.display.$value.join(', ') },
    radius: Object.fromEntries(Object.entries(base.brand.radius).filter(([k]) => !k.startsWith('$')).map(([k, v]) => [k, `${v.$value.value}${v.$value.unit}`])),
    modes,
  });
}

/* ------------------------------------------------------ contrast audit */
function luminance(hex) {
  const h = hex.replace('#', '');
  if (!/^[0-9a-f]{6}$/i.test(h)) return null;
  const [r, g, b] = [0, 2, 4]
    .map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
    .map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrast(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  if (la == null || lb == null) return null;
  return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05);
}

// [foreground, background, minimum]. 4.5 = text, 3 = large text / UI graphics (WCAG 1.4.3 + 1.4.11)
const PAIRS = [
  ['foreground', 'background', 4.5],
  ['card-foreground', 'card', 4.5],
  ['popover-foreground', 'popover', 4.5],
  ['secondary-foreground', 'secondary', 4.5],
  ['muted-foreground', 'muted', 4.5],
  ['muted-foreground', 'card', 4.5],
  ['subtle-foreground', 'card', 3],
  ['primary-foreground', 'primary', 4.5],
  ['accent-foreground', 'accent', 4.5],
  ['highlight-foreground', 'highlight', 4.5],
  ['sidebar-accent-foreground', 'sidebar-accent', 4.5],
  ['primary', 'card', 3],
  ['primary', 'background', 3],
  ['ring', 'card', 3],
  ['input', 'card', 3],
  ['destructive-foreground', 'destructive', 4.5],
  ['destructive', 'card', 4.5],
  ['destructive', 'destructive-soft', 4.5],
  ['success', 'success-soft', 4.5],
  ['warning', 'warning-soft', 4.5],
  ['info', 'info-soft', 4.5],
  ['success', 'card', 3],
  ['chart-1', 'card', 3],
  ['chart-2', 'card', 3],
];

const audit = [];
for (const b of brands) {
  for (const mode of MODES) {
    for (const [fg, bg, min] of PAIRS) {
      const ratio = contrast(b.modes[mode][fg].value, b.modes[mode][bg].value);
      if (ratio == null) throw new Error(`Cannot audit ${b.id}/${mode} ${fg} on ${bg}: non-hex value`);
      audit.push({ brand: b.id, mode, fg, bg, ratio: Math.round(ratio * 100) / 100, min, pass: ratio >= min });
    }
  }
}
const failures = audit.filter((a) => !a.pass);

/* ------------------------------------------------------------- outputs */
const primitives = readJson('tokens/primitives.json').palette;
const palette = Object.fromEntries(
  Object.entries(primitives)
    .filter(([k, v]) => !k.startsWith('$') && !('$value' in v))
    .map(([hue, steps]) => [hue, Object.fromEntries(Object.entries(steps).map(([s, t]) => [s, t.$value]))]),
);

const ts = `/* GENERATED by scripts/build-tokens.mjs from tokens/**.json (W3C DTCG). Do not edit. */
export const brands = ${JSON.stringify(brands, null, 2)} as const;

export const semanticTokenNames = ${JSON.stringify(Object.keys(brands[0].modes.light))} as const;

export const palette = ${JSON.stringify(palette, null, 2)} as const;

export const contrastAudit = ${JSON.stringify(audit)} as const;
`;

mkdirSync(join(root, 'src/styles'), { recursive: true });
mkdirSync(join(root, 'src/tokens'), { recursive: true });
writeFileSync(join(root, 'src/styles/tokens.css'), css);
writeFileSync(join(root, 'src/tokens/tokens.generated.ts'), ts);

const count = Object.keys(brands[0].modes.light).length;
console.log(`✔ tokens: ${brands.length} brand(s) × ${MODES.length} modes, ${count} semantic colours (Style Dictionary, DTCG)`);
console.log(`✔ contrast audit: ${audit.length - failures.length}/${audit.length} pairs pass WCAG AA`);
if (failures.length) {
  for (const a of failures) console.error(`  ✖ ${a.brand}/${a.mode}: ${a.fg} on ${a.bg} = ${a.ratio} (min ${a.min})`);
  process.exitCode = 1;
}
